---@type string, G_RLF
local addonName, G_RLF = ...

---@module 'strings'

---@class G_RLF
---@field public addonVersion string
---@field public localeName string
---@field public lsm table
---@field public acd AceConfigDialog
---@field public DBIcon table
---@field public RLF RPGLootFeed
---@field public AuctionIntegrations AuctionIntegrations
---@field public cachedArmorClass number | nil
---@field public ClassicToRetail ClassicToRetail
---@field public db table<string, table<string, any>>
---@field public defaults table<string, table<string, any>>
---@field public ItemInfo RLF_ItemInfo
---@field public L table<string, string>
---@field public LootDisplay LootDisplay
---@field public list list
---@field public Masque table
---@field public iconGroup table
---@field public migrations table
---@field public moduleName string
---@field public options table
---@field public Queue Queue
---@field public DbMigrations RLF_DbMigrations
---@field public tempFontString FontString | nil
---@field public Expansion table<string, number>
---@field public DisableBossBanner table<string, number>
---@field public FontFlags table<string, string>
---@field public ItemQualEnum table<string, number>
---@field public LogEventSource table<string, string>
---@field public LogLevel table<string, string>
---@field public FeatureModule table<string, string>
---@field public PricesEnum table<string, string>
---@field public EnterAnimationType table<string, string>
---@field public ExitAnimationType table<string, string>
---@field public SlideDirection table<string, string>
---@field public WrapCharEnum table<string, number>
---@field public WrapCharOptions table<number, string>
---@field public GameSounds table<string, number>
---@field public armorClassMapping table<number, number>
---@field public equipSlotMap table<string, number | table<number, number>>
---@field public hiddenCurrencies table<number, boolean>
---@field public mainFeatureOrder table<string, number>
---@field public OpenOptions fun(self: G_RLF, button: string): any
---@field public fn fun(self: G_RLF | AceModule, func: function, ...: any): any
---@field public retryHook fun(module: AceTimer, previousAttempts: number, hookFunctionName: string, localeKey: string): number
---@field public NotifyChange fun(self: G_RLF, ...: any): any
---@field public Print fun(self: G_RLF, ...: any): any
---@field public IsRetail fun(self: G_RLF): boolean
---@field public IsClassic fun(self: G_RLF): boolean
---@field public IsCataClassic fun(self: G_RLF): boolean
---@field public SendMessage fun(self: G_RLF, ...: any): any
---@field public RGBAToHexFormat fun(self: G_RLF, r: number, g: number, b: number, a: number): string
---@field public LogDebug fun(self: G_RLF, ...: any): any
---@field public LogInfo fun(self: G_RLF, ...: any): any
---@field public LogWarn fun(self: G_RLF, ...: any): any
---@field public LogError fun(self: G_RLF, ...: any): any
---@field public CreatePatternSegmentsForStringNumber fun(self: G_RLF, localeString: string): table<number, string>
---@field public ExtractDynamicsFromPattern fun(self: G_RLF, localeString: string, segments: table<number, string>): string | nil, number | nil
---@field public TableToCommaSeparatedString fun(self: G_RLF, t: table<string, string>): string
---@field public FontFlagsToString fun(self: G_RLF): string
---@field public ProfileFunction fun(self: G_RLF, f: function, s: string): fun(...: any): any
---@field public CalculateTextWidth fun(self: G_RLF, text: string): number
---@field public TruncateItemLink fun(self: G_RLF, itemLink: string, extraWidth: number): string
---@field public ShouldRunMigration fun(self: G_RLF, migration: number): boolean
---@field public InitializeLootDisplayProperties fun(element: RLF_LootElement)
---@field public LootDisplayProperties string[]
