[SIZE=4]RPGLootFeed[/SIZE]

[URL="https://github.com/Mctalian/RPGLootFeed/releases/latest"][IMG]https://img.shields.io/github/v/release/McTalian/RPGLootFeed?style=for-the-badge[/IMG][/URL] [IMG]https://img.shields.io/curseforge/game-versions/1082791?style=for-the-badge&logo=battledotnet[/IMG] [URL="https://www.curseforge.com/wow/addons/rpglootfeed"][IMG]https://img.shields.io/curseforge/dt/1082791?style=for-the-badge&logo=curseforge&label=Downloads[/IMG][/URL]

[URL="https://github.com/Mctalian/RPGLootFeed/issues?q=is%3Aissue+is%3Aopen+-label%3Ai18n"][IMG]https://img.shields.io/github/issues-search/McTalian/RPGLootFeed?query=is%3Aissue%20is%3Aopen%20-label%3Ai18n&style=for-the-badge&label=Open%20Tickets[/IMG][/URL] [URL="https://github.com/Mctalian/RPGLootFeed/issues?q=is%3Aissue+is%3Aopen+-label%3Ai18n+label%3Abug"][IMG]https://img.shields.io/github/issues-search/McTalian/RPGLootFeed?query=is%3Aissue%20is%3Aopen%20-label%3Ai18n%20label%3Abug&style=for-the-badge&label=Known%20Bugs&color=red[/IMG][/URL] [URL="https://github.com/Mctalian/RPGLootFeed/issues?q=is%3Aissue+is%3Aopen+label%3Ai18n"][IMG]https://img.shields.io/github/issues-search/McTalian/RPGLootFeed?query=is%3Aissue%20is%3Aopen%20label%3Ai18n%20&style=for-the-badge&label=Locales%20Need%20Translation&color=orange[/IMG][/URL]

[URL="https://discord.gg/czRYVWhe33"][IMG]https://img.shields.io/discord/1349872309665660928?style=for-the-badge&logo=discord&label=Join%20the%20Community[/IMG][/URL]

RPGLootFeed is a World of Warcraft addon designed to declutter your chat and enhance your looting experience by providing a dynamic and immersive loot feed. Keep your chat just for chat and let RPGLootFeed handle the rest.

As featured in SoulSoBreezy's [I]11 Useful Addons for Patch 11.0.7[/I]
[URL="https://youtu.be/GFr01R3TkmE?si=Wgw5F3AtenWdC08U&t=84"][IMG]https://img.youtube.com/vi/GFr01R3TkmE/hqdefault.jpg[/IMG][/URL]

[SIZE=3]Features[/SIZE]

- [B]Declutter Your Chat[/B]: Keep your chat window free from loot spam. RPGLootFeed displays all your looted items, currencies, reputation gains, and even profession skill-ups in a sleek, scrolling feed.
- [B]Contextual Information[/B]: Get detailed information about looted items, currencies, and faction reputation gains. See the item count available to your character, currency cap information, reputation progress, and more at a glance.
- [B]Integrations[/B]: Seamlessly integrates with popular addons like ElvUI, Auctionator, TradeSkillMaster (TSM) to provide additional contextual information and enhance your looting experience. Or apply your favorite Masque themes to RPGLootFeed so it fits in nicely with your custom UI experience.
- [B]Customizable[/B]: Tailor the loot feed to your preferences. Choose what information to display and how it should be presented.

[SIZE=3]Recommended Addons[/SIZE]

Pair RPGLootFeed with Speedy AutoLoot by Yuyuli for an even better looting experience. Speed up looting by not showing the loot frame.

- [URL="https://www.curseforge.com/wow/addons/speedyautoloot"]Speedy AutoLoot on CurseForge[/URL]
- [URL="https://addons.wago.io/addons/speedy-autoloot"]Speedy AutoLoot on Wago[/URL]

[SIZE=3]Installation[/SIZE]

1. Download the latest release from [URL="https://github.com/Mctalian/RPGLootFeed/releases/latest"]GitHub[/URL] or right here on WoW Interface.
2. Extract the downloaded file into your World of Warcraft Interface/AddOns directory.
3. Restart World of Warcraft and enable RPGLootFeed in the AddOns menu.

[SIZE=3]Contributing[/SIZE]

Contributions are welcome from the community! If you encounter any issues or have suggestions for improvements, please open an issue on [URL="https://github.com/Mctalian/RPGLootFeed/issues"]GitHub[/URL]. Or head over to [URL="https://github.com/Mctalian/RPGLootFeed/discussions"]Discussions[/URL] if you have any questions or want to show off your UI. 

For the fastest response, join the [URL="https://discord.gg/czRYVWhe33"]Discord Community[/URL].

[SIZE=3]License[/SIZE]

RPGLootFeed is licensed under the MIT License.

[SIZE=3]Screenshots[/SIZE]

[IMG]https://github.com/Mctalian/RPGLootFeed/raw/main/example-feed.png[/IMG]

[IMG]https://github.com/Mctalian/RPGLootFeed/raw/main/RLF_test_mode.gif[/IMG]

[IMG]https://github.com/Mctalian/RPGLootFeed/raw/main/example-loot-history.png[/IMG]
