name: Bug Report
description: Create a report to help us fix a bug in the project.
title: "[Bug]: "
labels:
  - bug
assignees:
  - McTalian

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below so we can investigate the issue.

  - type: checkboxes
    id: flavor
    attributes:
      label: Game Flavor
      description: Which game flavor(s) does this bug occur in? (Check all that you are aware of)
      options:
        - label: Retail
        - label: Cataclysm Classic
        - label: Classic Era (Vanilla)
        - label: Classic Era, Season of Discovery
        - label: Classic Era 20th Anniversary (Vanilla)
        - label: Other (please specify in additional information section)
    validations:
      required: true

  - type: checkboxes
    id: locale
    attributes:
      label: Game Locale
      description: Which game locale(s) does this bug occur in? (Check all that you are aware of)
      options:
        - label: enUS
        - label: enGB
        - label: deDE
        - label: frFR
        - label: esES
        - label: esMX
        - label: ptBR
        - label: ruRU
        - label: koKR
        - label: zhCN
        - label: zhTW
    validations:
      required: true

  - type: checkboxes
    id: rlf-version
    attributes:
      label: RLF Version
      description: Which version of RPGLootFeed did you encounter this bug?
      options:
        - label: I am using the latest version from CurseForge, Wago, WoWInterface, or GitHub.
        - label: I am using an older version (please specify in additional information section)
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Did this occur when you logged in? When you looted something? Does it only occur when you have a certain options configured?
      placeholder: |
        1. Enable party loot
        2. Join a party
        3. Party member loots an item
        4. The text overlaps with the party member's icon
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Any additional context, game flavors, RPGLootFeed version(s), screenshots, or logs (`/rlf log` in game).
      placeholder: Add any other context about the problem here.
