name: Feature Request
description: Suggest a new feature or enhancement for RPGLootFeed
title: "[Feature Request]: "
labels:
  - enhancement
assignees:
  - McTalian

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature or enhancement for RPGLootFeed. Please provide the following information to help us understand and evaluate your request.

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Describe the feature in detail. Include any relevant context, examples, use cases, etc.
      placeholder: Provide a detailed description of the feature...
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Provide any additional context or information that may be helpful in evaluating the feature request.
      placeholder: Add any other context about the feature request here..., e.g. screenshots, logs, etc.
