name: Main

on:
  push:
    branches:
      - main
      - ([0-9]+)?(.{([0-9]+),x}).x # 1.x, 1.2.x, 1.x.x

permissions: {}

jobs:
  ci:
    permissions:
      contents: write
      actions: write
      pull-requests: write
      issues: write
    uses: McTalian-WoW-Addons/wow-build-tools/.github/workflows/ci.yml@feat/phase-5-consolidation
    with:
      addon-name: RPGLootFeed
      rockspec-name: rpglootfeed-1-1.rockspec
      lua-version: 5.3.5
      i18n-enabled: true
      wbt-ref: feat/phase-5-consolidation
    secrets: inherit
