name: Package and release

on:
  release:
    types:
      - published

permissions: {}

jobs:
  package-and-release:
    uses: McTalian-WoW-Addons/.github/.github/workflows/package-and-distribute.yml@main
    with:
      addon-name: RPGLootFeed
      avatar-url: https://raw.githubusercontent.com/McTalian-WoW-Addons/RPGLootFeed/refs/heads/main/RPGLootFeed_logo.png
    secrets: inherit
