name: PR Checks

on:
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

permissions: {}

jobs:
  pr-checks:
    permissions:
      contents: read
      actions: write
      pull-requests: write
      checks: write
    uses: McTalian-WoW-Addons/wow-build-tools/.github/workflows/pr-checks.yml@v1-beta
    with:
      addon-name: RPGLootFeed
      rockspec-name: rpglootfeed-1-1.rockspec
      i18n-enabled: true
      i18n-ignore-files: IntegrationTest.lua SmokeTest.lua
      trunk-enabled: true
    secrets: inherit
