name: Package and release

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GH_PAT }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: subversion
          version: test_package_apt_cache

      - name: Package and release
        uses: BigWigsMods/packager@v2
