name: Package and release

on:
  release:
    types:
      - published

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # env:
    #   CF_API_KEY: ${{ secrets.CF_API_KEY }}
    #   WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
    #   WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: subversion
          version: test_package_apt_cache

      - name: Package and release
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN}}
        uses: McTalian/wow-build-tools@5725297073cc9b963b3952f5b1e306130489fe24
        with:
          args: -V
