name: Package and release

on:
  release:
    types:
      - published

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_OAUTH: ${{ secrets.GH_PAT}}
    #   CF_API_KEY: ${{ secrets.CF_API_KEY }}
    #   WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
    #   WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and release
        env:
        uses: McTalian/wow-build-tools@7be05c4124a005bd584cd36e4ee1e86e141f9466
        with:
          args: -V
