name: Package and release

on:
  release:
    types:
      - published

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      # CF_API_KEY: ${{ secrets.CF_API_KEY }}
      # WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      # WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GH_PAT }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: subversion
          version: test_package_apt_cache

      # - name: Package and release
      #   uses: BigWigsMods/packager@v2

      - name: Package and release
        uses: McTalian/wow-build-tools@64db80ff71af37c12132fa75eef08b5b384e1cf6
        with:
          args: -V
