name: Update TOC Interface version(s)

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *

permissions: {}

jobs:
  toc-update:
    uses: McTalian-WoW-Addons/wow-build-tools/.github/workflows/toc-updater.yml@v1-beta
    with:
      addon-name: RPGLootFeed
      pr-body: |
        ## Requirements

        - [ ] Download test package in the comments below
        - [ ] Test for all applicable game clients
          - [ ] Retail (PTR? Beta?)
          - [ ] Classic (PTR? Beta?)
          - [ ] Classic Anniversary (PTR? Beta?)
          - [ ] Classic Era (PTR? Beta?)

        ----------------------------------------------------
        _This PR was automatically created to update the supported interface versions in RPGLootFeed.toc._
    secrets: inherit
